services:
  - docker

script:
  - docker run --rm -t -v "$(readlink -f .):/src" "$(docker build -q docker)" bash -c 'mkdir /tmp/build && cd /tmp/build && cmake  -DBUILD_TESTING=True -GNinja /src && ninja'
