name: CI

on:
  push:
    branches:
      - openssl1.1
      # Just for testing (TODO: remove)
      - github-actions-wip
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["g++"]
        build_type: [""]
        allowed_to_fail: [false]
        include:
          # Currently, tests fail when ASAN is enabled or when clang is used.
          # Until this is fixed, failures in matrix entries does not fail the
          # build. TODO: Fix this.
          - compiler: "clang"
            build_type: "ASAN"
            allowed_to_fail: true
          - compiler: "g++"
            build_type: "ASAN"
            allowed_to_fail: true
          - compiler: "clang++"
            build_type: ""
            allowed_to_fail: true
    continue-on-error: ${{ matrix.allowed_to_fail }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Load Docker cache"
        uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          # Maintain a separate cache for each branch (base_ref is the PR
          # target branch):
          key: docker-layer-caching-${{ github.base_ref }}-{hash}
          restore-keys: |
            docker-layer-caching-${{ github.base_ref }}
            docker-layer-caching-

      - name: "Build Docker image"
        run: |
          docker build -t buildenv - < .github/Dockerfile

      - name: "Build MoCOCrW"
        run: |
          mkdir build
          docker run --rm -u $UID -v $PWD:/src:rw -w /src/build buildenv bash -c \
            'cmake \
              -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DBUILD_TESTING=True \
              -GNinja \
              /src \
            && ninja'

      - name: "Run tests"
        run: |
          docker run --rm -u $UID -v $PWD:/src:rw -w /src/build buildenv bash -c 'ctest -j $(nproc)'
