name: CI

on:
  push:
    branches:
      - openssl1.1
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["g++", "clang++"]
        flags: ["", "-fsanitize=address,leak,undefined"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Load Docker cache"
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: "Build Docker image"
        run: |
          docker build -t buildenv - < .github/Dockerfile

      - name: "Build MoCOCrW"
        run: |
          mkdir build
          docker run --rm -u $UID -v $PWD:/src:rw -w /src/build buildenv bash -c \
            'cmake \
              -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
              -DCMAKE_CXX_FLAGS=${{ matrix.flags }} \
              -DBUILD_TESTING=True \
              -GNinja \
              /src \
            && ninja'

      - name: "Run tests"
        run: |
          docker run --rm -u $UID -v $PWD:/src:rw -w /src/build buildenv bash -c 'ctest -j $(nproc)'
